# Form implementation generated from reading ui file '/home/adrian/repos/Projekt_IO/gui/zawartosc/designer/ustawienia_zasobow_designer.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 200)
        self.suwak = QtWidgets.QSlider(Dialog)
        self.suwak.setGeometry(QtCore.QRect(30, 100, 651, 41))
        self.suwak.setMinimum(1)
        self.suwak.setMaximum(10)
        self.suwak.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.suwak.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.suwak.setTickInterval(1)
        self.suwak.setObjectName("suwak")
        self.wartosc = QtWidgets.QLabel(Dialog)
        self.wartosc.setGeometry(QtCore.QRect(700, 110, 59, 20))
        self.wartosc.setObjectName("wartosc")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 741, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.wartosc.setText(_translate("Dialog", "1"))
        self.label_2.setText(_translate("Dialog", "Ilość rdzeni używanych do analizy"))
